title: Workstream X | The Delta Group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: ""
google_analytics: "UA-24138326-8"
scroll_speed: 400
sass:
  style: compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  sections:
    output: false
  features:
    output: false
defaults:
  - scope:
      path: ''
      type: sections
    values:
      title: ""
      include: ""
      position:
  - scope:
      path: ''
      type: features
    values:
      title: ""
      video: ""
      video_description: ""
      position:
